name: gitea
description: "Gitea"
containers:
  - name: bpi/act-runner
    ref: bozemanpass/gitea-containers@main
    path: ./act-runner
  - name: bpi/gitea
    ref: bozemanpass/gitea-containers@main
    path: ./gitea
pods:
  - name: gitea
    path: gitea
    pre_start_command: "run-this-first.sh"
    post_start_command: "initialize-gitea.sh"
  - name: act-runner
    path: act-runner
    pre_start_command: "pre_start.sh"
    post_start_command: "post_start.sh"
