version: "1.1"
name: gitea
description: "Gitea"
repos:
  - github.com/telackey/gitea@telackey/sort
  - github.com/telackey/gitea-stack
containers:
  - bpi/gitea
pods:
  - name: gitea
    repository: telackey/gitea-stack
    path: gitea
    pre_start_command: "run-this-first.sh"
    post_start_command: "initialize-gitea.sh"
