
services:
  runner:
    image: bpi/act-runner:local
    restart: always
    environment:
      - CONFIG_FILE=/config/act-runner-config.yml
      # Note: eMdEwIzSo87nBh0UFWZlbp308j6TNWr3WhWxQqIc is a static token we use for convenience in stand-alone deployments. Not secure, obviously.
      - GITEA_RUNNER_REGISTRATION_TOKEN=${BPI_GITEA_RUNNER_REGISTRATION_TOKEN:-eMdEwIzSo87nBh0UFWZlbp308j6TNWr3WhWxQqIc}
      - GITEA_INSTANCE_URL=${BPI_GITEA_INSTANCE_URL:-http://localhost:3000}
      - GITEA_RUNNER_LABELS=${BPI_GITEA_RUNNER_LABELS:-ubuntu-latest:docker://bpi/act-runner-task-executor:local,ubuntu-22.04:docker://bpi/act-runner-task-executor:local}
    volumes:
      - act-runner-data:/data
      - act-runner-config:/config:ro
    ports:
      - 8088

volumes:
  act-runner-data:
  act-runner-config:
